# Site settings
title: Simple CSV.js
email: baris@onehundredyearsofcode.com
description: >
  Fastest standalone JavaScript CSV parser
  <br>Full Python 2.7 csv parser compatibility
  <br>Full JSON support
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simplecsvjs.com" # the base hostname & protocol for your site
twitter_username: baris_wonders
github_username:  byuksel

# Build settings
markdown: kramdown
